import 'package:equatable/equatable.dart';

class ProductEntity extends Equatable {
  final String id;
  final String name;
  final String brand;
  final String categoryId;
  final String description;
  final String composition;
  final List<String> uses;
  final List<String> sideEffects;
  final double price;
  final double mrp;
  final int discount;
  final List<String> imageUrls;
  final bool requiresPrescription;
  final bool inStock;
  final int stockCount;
  final double rating;
  final int reviewCount;
  final List<String> tags;

  const ProductEntity({
    required this.id,
    required this.name,
    required this.brand,
    required this.categoryId,
    required this.description,
    required this.composition,
    required this.uses,
    required this.sideEffects,
    required this.price,
    required this.mrp,
    required this.discount,
    required this.imageUrls,
    required this.requiresPrescription,
    required this.inStock,
    required this.stockCount,
    required this.rating,
    required this.reviewCount,
    required this.tags,
  });

  @override
  List<Object?> get props => [id, name, brand, price, inStock];

  factory ProductEntity.fromMap(Map<String, dynamic> map) {
    return ProductEntity(
      id: map['id'] as String? ?? '',
      name: map['name'] as String? ?? '',
      brand: map['brand'] as String? ?? '',
      categoryId: map['categoryId'] as String? ?? '',
      description: map['description'] as String? ?? '',
      composition: map['composition'] as String? ?? '',
      uses: List<String>.from(map['uses'] ?? []),
      sideEffects: List<String>.from(map['sideEffects'] ?? []),
      price: (map['price'] as num?)?.toDouble() ?? 0.0,
      mrp: (map['mrp'] as num?)?.toDouble() ?? 0.0,
      discount: map['discount'] as int? ?? 0,
      imageUrls: List<String>.from(map['imageUrls'] ?? []),
      requiresPrescription: map['requiresPrescription'] as bool? ?? false,
      inStock: map['inStock'] as bool? ?? true,
      stockCount: map['stockCount'] as int? ?? 0,
      rating: (map['rating'] as num?)?.toDouble() ?? 0.0,
      reviewCount: map['reviewCount'] as int? ?? 0,
      tags: List<String>.from(map['tags'] ?? []),
    );
  }

  Map<String, dynamic> toMap() => {
        'id': id,
        'name': name,
        'brand': brand,
        'categoryId': categoryId,
        'description': description,
        'composition': composition,
        'uses': uses,
        'sideEffects': sideEffects,
        'price': price,
        'mrp': mrp,
        'discount': discount,
        'imageUrls': imageUrls,
        'requiresPrescription': requiresPrescription,
        'inStock': inStock,
        'stockCount': stockCount,
        'rating': rating,
        'reviewCount': reviewCount,
        'tags': tags,
      };
}

// Mock products for development
class MockProducts {
  static final List<ProductEntity> all = [
    const ProductEntity(
      id: 'p1',
      name: 'Dolo 650mg',
      brand: 'Micro Labs',
      categoryId: 'pain-relief',
      description: 'Dolo 650 is a pain reliever and fever reducer. It contains Paracetamol 650mg.',
      composition: 'Paracetamol 650mg',
      uses: ['Fever', 'Headache', 'Body ache', 'Toothache'],
      sideEffects: ['Nausea', 'Rash (rare)', 'Liver damage (overdose)'],
      price: 30,
      mrp: 36,
      discount: 17,
      imageUrls: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80'],
      requiresPrescription: false,
      inStock: true,
      stockCount: 500,
      rating: 4.8,
      reviewCount: 12540,
      tags: ['fever', 'pain', 'paracetamol'],
    ),
    const ProductEntity(
      id: 'p2',
      name: 'Crocin 500mg',
      brand: 'GSK',
      categoryId: 'pain-relief',
      description: 'Crocin 500 tablet is used to reduce fever and relieve mild to moderate pain.',
      composition: 'Paracetamol 500mg',
      uses: ['Fever', 'Common cold', 'Mild pain'],
      sideEffects: ['Nausea', 'Stomach upset (rare)'],
      price: 28,
      mrp: 32,
      discount: 12,
      imageUrls: ['https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=400&q=80'],
      requiresPrescription: false,
      inStock: true,
      stockCount: 300,
      rating: 4.6,
      reviewCount: 8920,
      tags: ['fever', 'pain', 'paracetamol'],
    ),
    const ProductEntity(
      id: 'p3',
      name: 'Pan D',
      brand: 'Alkem',
      categoryId: 'gastro',
      description: 'Pan D capsule is used to treat acidity, heartburn, and stomach ulcers.',
      composition: 'Pantoprazole 40mg + Domperidone 10mg',
      uses: ['Acidity', 'Heartburn', 'GERD', 'Bloating'],
      sideEffects: ['Headache', 'Diarrhea', 'Dizziness'],
      price: 88,
      mrp: 105,
      discount: 16,
      imageUrls: ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=400&q=80'],
      requiresPrescription: false,
      inStock: true,
      stockCount: 200,
      rating: 4.5,
      reviewCount: 5630,
      tags: ['acidity', 'gastro', 'pantoprazole'],
    ),
    const ProductEntity(
      id: 'p4',
      name: 'Allegra 120mg',
      brand: 'Sanofi',
      categoryId: 'allergy',
      description: 'Allegra 120mg tablet is used to relieve allergy symptoms such as sneezing, runny nose, and itchy eyes.',
      composition: 'Fexofenadine 120mg',
      uses: ['Allergic rhinitis', 'Sneezing', 'Itchy eyes', 'Skin rash'],
      sideEffects: ['Headache', 'Drowsiness', 'Nausea'],
      price: 145,
      mrp: 175,
      discount: 17,
      imageUrls: ['https://images.unsplash.com/photo-1607619275068-24722480f875?auto=format&fit=crop&w=400&q=80'],
      requiresPrescription: false,
      inStock: true,
      stockCount: 150,
      rating: 4.4,
      reviewCount: 3210,
      tags: ['allergy', 'antihistamine'],
    ),
    const ProductEntity(
      id: 'p5',
      name: 'Vitamin D3 60K',
      brand: 'Sun Pharma',
      categoryId: 'vitamins',
      description: 'Vitamin D3 60000 IU capsule helps treat and prevent Vitamin D deficiency.',
      composition: 'Cholecalciferol 60000 IU',
      uses: ['Vitamin D deficiency', 'Bone health', 'Immunity'],
      sideEffects: ['Nausea (rare)', 'Hypercalcemia (overdose)'],
      price: 65,
      mrp: 80,
      discount: 19,
      imageUrls: ['https://images.unsplash.com/photo-1611926653458-09294b3142bf?auto=format&fit=crop&w=400&q=80'],
      requiresPrescription: false,
      inStock: true,
      stockCount: 400,
      rating: 4.7,
      reviewCount: 7890,
      tags: ['vitamin', 'immunity', 'bone health'],
    ),
    const ProductEntity(
      id: 'p6',
      name: 'Azithromycin 500',
      brand: 'Cipla',
      categoryId: 'antibiotics',
      description: 'Azithromycin 500mg is an antibiotic used to treat bacterial infections.',
      composition: 'Azithromycin 500mg',
      uses: ['Throat infection', 'Chest infection', 'Ear infection'],
      sideEffects: ['Stomach pain', 'Diarrhea', 'Nausea'],
      price: 95,
      mrp: 120,
      discount: 21,
      imageUrls: ['https://images.unsplash.com/photo-1550572017-edd951b55104?auto=format&fit=crop&w=400&q=80'],
      requiresPrescription: true,
      inStock: true,
      stockCount: 100,
      rating: 4.3,
      reviewCount: 2140,
      tags: ['antibiotic', 'infection'],
    ),
    // ── SKINCARE ─────────────────────────────────────────────
    const ProductEntity(
      id: 'sk1',
      name: 'Cetaphil Gentle Skin Cleanser',
      brand: 'Cetaphil',
      categoryId: 'skincare',
      description: 'Dermatologist recommended #1 gentle cleanser for sensitive & dry skin. Soap-free, non-irritating formula that hydrates while cleansing.',
      composition: 'Cetyl Alcohol, Propylene Glycol, SLS, Purified Water',
      uses: ['Daily face cleansing', 'Sensitive skin care', 'Barrier protection'],
      sideEffects: ['None reported'],
      price: 310,
      mrp: 375,
      discount: 17,
      imageUrls: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80'],
      requiresPrescription: false,
      inStock: true,
      stockCount: 320,
      rating: 4.8,
      reviewCount: 28400,
      tags: ['cleanser', 'skincare', 'dry skin', 'cetaphil', 'sensitive'],
    ),
    const ProductEntity(
      id: 'sk2',
      name: 'Minimalist 10% Niacinamide Serum',
      brand: 'Minimalist',
      categoryId: 'skincare',
      description: 'India\'s #1 selling face serum. Reduces acne marks, controls oil, and visibly shrinks pores. Dermatologist tested.',
      composition: 'Niacinamide 10% + Zinc 1%',
      uses: ['Acne marks reduction', 'Oil control', 'Pore minimizing', 'Skin brightening'],
      sideEffects: ['Mild tingling (first use)'],
      price: 399,
      mrp: 599,
      discount: 33,
      imageUrls: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=400&q=80'],
      requiresPrescription: false,
      inStock: true,
      stockCount: 450,
      rating: 4.6,
      reviewCount: 52000,
      tags: ['serum', 'skincare', 'glowing skin', 'niacinamide', 'minimalist'],
    ),
    const ProductEntity(
      id: 'sk3',
      name: 'Neutrogena Oil-Free Acne Wash',
      brand: 'Neutrogena',
      categoryId: 'skincare',
      description: 'Clinically proven acne face wash with 2% Salicylic Acid. Dermatologist #1 recommended brand for acne-prone skin.',
      composition: 'Salicylic Acid 2%, Aloe Vera Extract',
      uses: ['Acne treatment', 'Deep pore cleansing', 'Oil control', 'Blackhead removal'],
      sideEffects: ['Mild dryness (initial use)'],
      price: 450,
      mrp: 549,
      discount: 18,
      imageUrls: ['https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=400&q=80'],
      requiresPrescription: false,
      inStock: true,
      stockCount: 200,
      rating: 4.5,
      reviewCount: 18700,
      tags: ['cleanser', 'skincare', 'acne', 'neutrogena', 'salicylic acid'],
    ),
    const ProductEntity(
      id: 'sk4',
      name: 'Himalaya Neem Face Wash',
      brand: 'Himalaya Wellness',
      categoryId: 'skincare',
      description: 'India\'s most trusted herbal face wash. Purifies skin naturally with Neem & Turmeric. Prevents pimples and removes impurities.',
      composition: 'Neem Extract, Turmeric Extract',
      uses: ['Pimple prevention', 'Deep cleansing', 'Oil balancing', 'Daily use'],
      sideEffects: ['None reported'],
      price: 135,
      mrp: 160,
      discount: 15,
      imageUrls: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80'],
      requiresPrescription: false,
      inStock: true,
      stockCount: 800,
      rating: 4.4,
      reviewCount: 95000,
      tags: ['face wash', 'skincare', 'neem', 'himalaya', 'herbal'],
    ),
    const ProductEntity(
      id: 'sk5',
      name: 'Mamaearth Vitamin C Face Serum',
      brand: 'Mamaearth',
      categoryId: 'skincare',
      description: 'Brightens skin with 20% Vitamin C & Turmeric. Made Safe certified, toxin-free. India\'s favourite clean beauty serum.',
      composition: 'Vitamin C 20%, Turmeric, Hyaluronic Acid',
      uses: ['Skin brightening', 'Dark spot removal', 'Anti-aging', 'Hydration'],
      sideEffects: ['Mild sensitivity to sunlight'],
      price: 499,
      mrp: 699,
      discount: 28,
      imageUrls: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=400&q=80'],
      requiresPrescription: false,
      inStock: true,
      stockCount: 350,
      rating: 4.3,
      reviewCount: 67000,
      tags: ['serum', 'skincare', 'vitamin c', 'mamaearth', 'brightening'],
    ),
    // ── HAIRCARE ─────────────────────────────────────────────
    const ProductEntity(
      id: 'hc1',
      name: 'Scalpe Plus Anti-Dandruff Shampoo',
      brand: 'Glenmark',
      categoryId: 'haircare',
      description: 'Medicated anti-dandruff shampoo by Glenmark Pharma. Contains Ketoconazole & ZPTO — prescribed by dermatologists across India.',
      composition: 'Ketoconazole 2% + Zinc Pyrithione',
      uses: ['Dandruff elimination', 'Scalp itch relief', 'Fungal infection treatment'],
      sideEffects: ['Dryness (rare)'],
      price: 324,
      mrp: 380,
      discount: 14,
      imageUrls: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=400&q=80'],
      requiresPrescription: false,
      inStock: true,
      stockCount: 280,
      rating: 4.5,
      reviewCount: 12500,
      tags: ['shampoo', 'haircare', 'dandruff', 'glenmark', 'medicated'],
    ),
    const ProductEntity(
      id: 'hc2',
      name: 'Indulekha Bringha Hair Oil',
      brand: 'Indulekha',
      categoryId: 'haircare',
      description: 'Ayurvedic hair oil with Bringharaj & 9 herbs. Clinically proven to reduce hair fall by 50% in 4 months. Selfie comb applicator.',
      composition: 'Bringharaj, Coconut Oil, Svetakutaja, Amla',
      uses: ['Hair fall control', 'Hair growth stimulation', 'Scalp nourishment'],
      sideEffects: ['None reported'],
      price: 396,
      mrp: 440,
      discount: 10,
      imageUrls: ['https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&w=400&q=80'],
      requiresPrescription: false,
      inStock: true,
      stockCount: 400,
      rating: 4.4,
      reviewCount: 78000,
      tags: ['hair oil', 'haircare', 'hair growth', 'indulekha', 'ayurvedic'],
    ),
    const ProductEntity(
      id: 'hc3',
      name: 'Biotique Bio Kelp Shampoo',
      brand: 'Biotique',
      categoryId: 'haircare',
      description: '100% botanical extracts protein shampoo for falling hair. Strengthens hair from root with natural kelp protein.',
      composition: 'Sea Kelp, Neem, Bhringraj, Mint Leaf',
      uses: ['Hair strengthening', 'Hair fall prevention', 'Protein nourishment'],
      sideEffects: ['None reported'],
      price: 185,
      mrp: 249,
      discount: 25,
      imageUrls: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=400&q=80'],
      requiresPrescription: false,
      inStock: true,
      stockCount: 350,
      rating: 4.3,
      reviewCount: 34000,
      tags: ['shampoo', 'haircare', 'protein', 'biotique', 'herbal'],
    ),
    // ── BODYCARE ─────────────────────────────────────────────
    const ProductEntity(
      id: 'bc1',
      name: 'Vaseline Intensive Care Body Lotion',
      brand: 'Vaseline',
      categoryId: 'bodycare',
      description: 'India\'s #1 body lotion with micro-droplets of Vaseline Jelly. Heals dry skin in 5 days. Dermatologically tested.',
      composition: 'Petroleum Jelly Micro-droplets, Glycerin, Stearic Acid',
      uses: ['Intense dry skin relief', '48-hr moisturization', 'Cracked heel repair'],
      sideEffects: ['None reported'],
      price: 250,
      mrp: 310,
      discount: 19,
      imageUrls: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80'],
      requiresPrescription: false,
      inStock: true,
      stockCount: 500,
      rating: 4.6,
      reviewCount: 42000,
      tags: ['body lotion', 'bodycare', 'moisturizer', 'vaseline'],
    ),
    const ProductEntity(
      id: 'bc2',
      name: 'Nivea Nourishing Body Milk Lotion',
      brand: 'Nivea',
      categoryId: 'bodycare',
      description: 'Deep moisture body milk with Almond Oil for very dry skin. 48hr hydration with Nivea Deep Moisture serum.',
      composition: 'Almond Oil, Glycerin, Deep Moisture Serum',
      uses: ['Very dry skin repair', 'All-day moisturizing', 'Smooth soft skin'],
      sideEffects: ['None reported'],
      price: 299,
      mrp: 375,
      discount: 20,
      imageUrls: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80'],
      requiresPrescription: false,
      inStock: true,
      stockCount: 420,
      rating: 4.5,
      reviewCount: 38000,
      tags: ['body lotion', 'bodycare', 'moisturizer', 'nivea'],
    ),
  ];
}
