// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeVBshSrGHm3uTave-py0Yzg64wyA0U0E',
    appId: '1:875181118672:web:55b17b4734fcdbd9ad3ad5',
    messagingSenderId: '875181118672',
    projectId: 'klinixy-68521',
    authDomain: 'klinixy-68521.firebaseapp.com',
    storageBucket: 'klinixy-68521.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfz1UIhPNbTOWBcq8yG7szLpuh3qrGWdM',
    appId: '1:875181118672:android:d78e1b46c3c41c4dad3ad5',
    messagingSenderId: '875181118672',
    projectId: 'klinixy-68521',
    storageBucket: 'klinixy-68521.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_76EiYXh_z0nH0qdTCmkZZ34Qa4WEJZ0',
    appId: '1:875181118672:ios:ceddd6b5caee3de6ad3ad5',
    messagingSenderId: '875181118672',
    projectId: 'klinixy-68521',
    storageBucket: 'klinixy-68521.firebasestorage.app',
    iosBundleId: 'com.softrion.klinixy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_76EiYXh_z0nH0qdTCmkZZ34Qa4WEJZ0',
    appId: '1:875181118672:ios:ceddd6b5caee3de6ad3ad5',
    messagingSenderId: '875181118672',
    projectId: 'klinixy-68521',
    storageBucket: 'klinixy-68521.firebasestorage.app',
    iosBundleId: 'com.softrion.klinixy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeVBshSrGHm3uTave-py0Yzg64wyA0U0E',
    appId: '1:875181118672:web:55b17b4734fcdbd9ad3ad5',
    messagingSenderId: '875181118672',
    projectId: 'klinixy-68521',
    authDomain: 'klinixy-68521.firebaseapp.com',
    storageBucket: 'klinixy-68521.firebasestorage.app',
  );
}